apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: board-frontend-metrics
  labels:
    app: board-frontend
spec:
  selector:
    matchLabels:
      app: board-frontend
  endpoints:
  - port: http
    path: /metrics
    interval: 30s

